title: Martinsite
description: Nơi lưu trữ và phân tích dữ liệu các tác phẩm.
theme: minima

collections:
  books:
    output: true
    permalink: /books/:path/

defaults:
  - scope:
      path: ""
      type: "books"
    values:
      layout: "post"

markdown: kramdown
